repo: https://github.com/rabbit-ci/example-project.git
steps:
  -
    name: "Install homebrew"
    boxes:
      - jhcook/osx-elcapitan-10.11
    before_script: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    script: |
      brew help
