repo: https://github.com/rabbit-ci/example-project.git
steps:
  -
    name: "Install zsh"
    boxes:
      - gce
    before_script: |
      sudo apt-get update
      sudo apt-get install -y git
    script: |
      git rev-parse HEAD
      sudo apt-get install -y zsh
      cat README.md
