repo: https://github.com/rabbit-ci/example-project.git
steps:
  -
    name: "`cat` the README file"
    boxes:
      - ubuntu/vivid64
    command: |
      git rev-parse HEAD
      cat README.md
  -
    name: "Show ubuntu version"
    boxes:
      - ubuntu/vivid64
    command: |
      git rev-parse HEAD
      lsb_release -a
      echo "Did it work?"
