repo: https://github.com/rabbit-ci/example-project.git
steps:
  -
    name: "Install zsh (slashy branch)"
    boxes:
      - ubuntu/vivid64
    script: |
      git rev-parse HEAD
      sudo apt-get install -y zsh
      cat README.md
